server:
  port: 8080
    
spring:
  application:
  name: "user-challenge"
  mvc:
    pathmatch:
      matching-strategy: "ant-path-matcher"
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:users;MODE=MySQL
    platform: h2

  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

jwt:
  secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
  validaty: 18000

regex:
  email: '[a-zA-Z0-9-_.]+@[a-zA-Z0-9-_.]+.cl'
  password:
    value: '(?=.*[0-9])(?=.*[a-z])(?=.*\d)(?=.*[#$@!%&*?]).{8,}'
    message: "La contraseña debe ser mayor de 8 dígitos, no contener espacios en blanco, debe tener al menos una letra mayúscula, debe tener al menos un carácter especial y debe tener al menos un número."