server:
  port: 8080
    
spring:
  application:
  name: "user-challenge"
  mvc:
    pathmatch:
      matching-strategy: "ant-path-matcher"
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:heroes;MODE=MySQL
    platform: h2

  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
